apiVersion: v1
kind: Pod
metadata: 
  name: secret-pod
  namespace: gulzat-secret
spec:
  containers:
  - name: busybox
    image: busybox:1.31.1
    command: ["/bin/sh", "-c", "while true; do echo hello; sleep 10; done"]
    env:
    - name: APP_USER
      valueFrom:
        secretKeyRef:
          name: secret2
          key: user
    - name: APP_PASS
      valueFrom:
        secretKeyRef:
          name: secret2
          key: pass
    volumeMounts:
    - name: secret-volume
      mountPath: "/tmp/secret1"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: secret1