apiVersion: v1
kind: Secret
metadata:
  name: secret1
  namespace: gulzat-secret
type: Opaque
data:
  username: dXNlcjE=
  password: cGFzczEyMzQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
  namespace: gulzat-secret
type: Opaque
data:
  user: dXNlcjE=
  pass: MTIzNA==